name: uhf_plugin_example
description: Demonstrates how to use the uhf_plugin plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  uhf_c72_plugin:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
